/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: '#0058be',
        'on-primary': '#ffffff',
        'primary-container': '#2170e4',
        'on-primary-container': '#fefcff',
        'primary-fixed': '#d8e2ff',
        'primary-fixed-dim': '#adc6ff',
        'on-primary-fixed': '#001a42',
        'on-primary-fixed-variant': '#004395',
        secondary: '#006c49',
        'on-secondary': '#ffffff',
        'secondary-container': '#6cf8bb',
        'on-secondary-container': '#00714d',
        'secondary-fixed': '#6ffbbe',
        'secondary-fixed-dim': '#4edea3',
        'on-secondary-fixed': '#002113',
        'on-secondary-fixed-variant': '#005236',
        tertiary: '#b61722',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#da3437',
        'on-tertiary-container': '#fffbff',
        'tertiary-fixed': '#ffdad7',
        'tertiary-fixed-dim': '#ffb3ad',
        'on-tertiary-fixed': '#410004',
        'on-tertiary-fixed-variant': '#930013',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#f8f9fa',
        'on-background': '#191c1d',
        surface: '#f8f9fa',
        'on-surface': '#191c1d',
        'surface-variant': '#e1e3e4',
        'on-surface-variant': '#424754',
        'surface-tint': '#005ac2',
        'surface-dim': '#d9dadb',
        'surface-bright': '#f8f9fa',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'surface-container': '#edeeef',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
        'inverse-primary': '#adc6ff',
        outline: '#727785',
        'outline-variant': '#c2c6d6',
      },
      fontFamily: {
        'headline-xl': ['Manrope', 'sans-serif'],
        'body-md': ['Work Sans', 'sans-serif'],
      },
      spacing: {
        'container-margin': '1rem',
        gutter: '1rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      boxShadow: {
        soft: '0px 4px 20px rgba(0, 0, 0, 0.05)',
        medium: '0px 8px 24px rgba(0, 0, 0, 0.08)',
      },
    },
  },
  plugins: [],
}